In [1]:
import torch

In [20]:
ds_path = '../_dataset/4.pt'

In [21]:
dataset = torch.load(ds_path)

In [22]:
dataset.keys()

dict_keys(['image', 'time', 'delay/image', 'delay/robot', 'ee_force', 'base_force', 'robot_joints', 'robot_position_trans', 'robot_position_quat'])

In [23]:
dataset['time']

tensor([0.0180, 0.0850, 0.1510, 0.2180, 0.2850, 0.3520, 0.4180, 0.4850, 0.5520,
        0.6190, 0.6860, 0.7520, 0.8190, 0.8850, 0.9520, 1.0200, 1.0860, 1.1530,
        1.2190, 1.2860, 1.3530, 1.4200, 1.4860, 1.5530, 1.6200, 1.6870, 1.7540,
        1.8210, 1.8880, 1.9540, 2.0210, 2.0880, 2.1540, 2.2210, 2.2880, 2.3550,
        2.4210, 2.4880, 2.5550, 2.6220, 2.6890, 2.7550, 2.8220, 2.8890, 2.9560,
        3.0230, 3.0900, 3.1570, 3.2230, 3.2900, 3.3570, 3.4240, 3.4900, 3.5580,
        3.6240, 3.6910, 3.7580, 3.8240, 3.8910, 3.9580, 4.0250, 4.0920, 4.1580,
        4.2250, 4.2920, 4.3590, 4.4250, 4.4930, 4.5590, 4.6260, 4.6930, 4.7600,
        4.8260, 4.8930, 4.9600, 5.0260, 5.0930, 5.1600, 5.2270, 5.2930, 5.3600,
        5.4270, 5.4940, 5.5610, 5.6270, 5.6940, 5.7610, 5.8280, 5.8940, 5.9620,
        6.0280, 6.0950, 6.1620], dtype=torch.float64)

In [24]:
dataset['delay/image'][:10]

tensor([0.1120, 0.1120, 0.1110, 0.1120, 0.1120, 0.1120, 0.1110, 0.1120, 0.1120,
        0.1120], dtype=torch.float64)

In [25]:
dataset['delay/robot'][:10]

tensor([0.0180, 0.0850, 0.0510, 0.0170, 0.0840, 0.0510, 0.0170, 0.0840, 0.0510,
        0.0180], dtype=torch.float64)

In [15]:
len(dataset['time'])

90

In [18]:
import sys
sys.path.append('..')
import geom

In [25]:
import numpy as np
import rerun as rr

In [28]:
tt = geom.Transform3D(np.array([1, 2, 3]), geom.Quaternion.from_euler(np.array([0, 0, 0])))

In [33]:
rr.Quaternion(xyzw=[tt.quaternion[1], tt.quaternion[2], tt.quaternion[3], tt.quaternion[0]])

Quaternion(xyzw=array([0., 0., 0., 1.], dtype=float32))

In [34]:
rr.Transform3D(translation=tt.translation, rotation=rr.Quaternion(xyzw=[tt.quaternion[1], tt.quaternion[2], tt.quaternion[3], tt.quaternion[0]]))

rr.Transform3D(
)